### PR TITLE
documentation extention attempt 1

### PR DESCRIPTION
**Pull request by themusicgod1**
see #28

### CODE REVIEW

**Comment by hellysmile** [comment]
As for me link to Python doc `functools.lru` might be enough. https://docs.python.org/3/library/functools.html#functools.lru_cache

**Comment by hellysmile** [comment]
Proposed readme changes is better, then nothing right now, but it is bring some mess as well.

Lets move all example related notes as comments into python example snippet and add link to python ‘functools.lru’

**Comment by themusicgod1** [comment]
I agree that that is a good compromise, but in the longer term I might as well state that what I'm aiming for is that sooner or later someone is going to look at this project as a package in a package manager, and they are going to want to understand what it is, why they need it, and whether or not it is legitimate for them to have in their system, even if they only have a general programming background(which I wouldn't suspect such people would necessarily know data structures like lru caches).

**Comment by hellysmile** [comment]
Going to close in in favor of of https://github.com/aio-libs/async_lru/pull/33 , feel free to create new PR, reopen this if needed

**Pull request closed without merging**
